In [7]:
# =========================================================
# TASK 1: Create DataFrames and Export Them as CSV Files
# =========================================================

In [8]:
# Import pandas and numpy library
import pandas as pd
import numpy as np

In [9]:
# Create employee data dictionary
employee_data = {
    "ID": ["A001", "A002", "A003", "A004", "A005"],
    "Name": ["John Alter", "Alice Luxumberg", "Tom Sabestine", "Nina Adgra", "Amy Johny"],
    "Gender": ["M", "F", "M", "F", "F"],
    "City": ["Paris", "London", "Berlin", "Newyork", "Madrid"],
    "Age": [25, 27, 29, 31, 30]
}

# Convert dictionary into DataFrame
employee_df = pd.DataFrame(employee_data)

# Display employee DataFrame
employee_df

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [10]:
# Create Seniority data dictionary
seniority_data = {
    "ID": ["A001", "A002", "A003", "A004", "A005"],
    "Designation Level": [2, 2, 3, 2, 3]
}

# Convert dictionary into DataFrame
seniority_df = pd.DataFrame(seniority_data)

# Display seniority DataFrame
seniority_df

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [11]:
# Create project data dictionary
project_data = {
    "ID": ["A001", "A002", "A003", "A004", "A005", "A002", "A005", "A003", "A001", "A003", "A001","A004", "A004", "A005"],
    "Project": ["Project 1", "Project 2", "Project 3", "Project 4", "Project 5", "Project 6", "Project 7", "Project 8", "Project 9", "Project 10", "Project 11", "Project 12", "Project 13", "Project 14"],
    "Cost": [100200, 2000000, 4500000, 5500000, None, 680000, 400000, 350000, None, 300000, 2000000, 1000000, 3000000, 200000],
    "Status": ["Finished", "Ongoing", "Finished", "Ongoing", "Finished", "Failed", "Finished", "Failed", "Ongoing", "Finished", "Failed", "Ongoing", "Finished", "Finished"]
}

# Convert dictionary into DataFrame
project_df = pd.DataFrame(project_data)

# Display project DataFrame
project_df

      ID     Project       Cost    Status
0   A001   Project 1   100200.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [12]:
# Save Employee DataFrame as employee.csv without row indexes
employee_df.to_csv("employee.csv", index=False)

# Save Seniority DataFrame as seniority.csv without row indexes
seniority_df.to_csv("seniority.csv", index=False)

# Save Project DataFrame as project.csv without row indexes
project_df.to_csv("project.csv", index=False)

In [13]:
# =========================================================
# TASK 2: Replace Missing Cost Values Using a Running Average
# =========================================================

In [14]:
# Read project data from project CSV file
project_df = pd.read_csv("project.csv")

# Variables used for running average calculation
total = 0
count = 0

# Loop through Cost column
for index, cost in enumerate(project_df["Cost"]):

    # Check if cost is not missing
    if not np.isnan(cost):

        # Add cost to running total
        total = total + cost

        # Increase count of valid values
        count = count + 1

    else:

        # Calculate running average
        average = total/count

        # Replace missing value with running average
        project_df.loc[index, "Cost"] = average

        # Add inserted value to running total
        total = total + average

        # Increase count after inserting value
        count = count + 1

# Save updated project DataFrame as project.csv without row indexes
project_df.to_csv("project.csv", index=False)

# Display Updated project DataFrame
project_df

      ID     Project        Cost    Status
0   A001   Project 1   100200.00  Finished
1   A002   Project 2  2000000.00   Ongoing
2   A003   Project 3  4500000.00  Finished
3   A004   Project 4  5500000.00   Ongoing
4   A005   Project 5  3025050.00  Finished
5   A002   Project 6   680000.00    Failed
6   A005   Project 7   400000.00  Finished
7   A003   Project 8   350000.00    Failed
8   A001   Project 9  2069406.25   Ongoing
9   A003  Project 10   300000.00  Finished
10  A001  Project 11  2000000.00    Failed
11  A004  Project 12  1000000.00   Ongoing
12  A004  Project 13  3000000.00  Finished
13  A005  Project 14   200000.00  Finished

In [15]:
# =========================================================
# TASK 3: Split the Name Column into First and Last Names
# =========================================================

In [16]:
# Read employee data from employee CSV file
employee_df = pd.read_csv("employee.csv")

# Create First Name column from Name column
employee_df["First Name"] = employee_df["Name"].str.split(" ").str[0]

# Create Last Name column from Name column
employee_df["Last Name"] = employee_df["Name"].str.split(" ").str[1]

# Delete old Name column
employee_df.drop("Name", axis=1, inplace=True)

# Save updated employee DataFrame as employee.csv without row indexes
employee_df.to_csv("employee.csv", index=False)

# Display updated DataFrame
employee_df

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [17]:
# =========================================================
# TASK 4: Merge All Three DataFrames into a Single DataFrame
# =========================================================

In [18]:
# Read employee data from employee.csv
employee_df = pd.read_csv("employee.csv")

# Read project data from project.csv
project_df = pd.read_csv("project.csv")

# Read seniority data from seniority.csv
seniority_df = pd.read_csv("seniority.csv")

# Merge employee and seniority data using ID
final_df = pd.merge(employee_df, seniority_df, on="ID")

# Merge project data with final dataframe using ID
final_df = pd.merge(final_df, project_df, on="ID")

# Save final dataframe for next task
final_df.to_csv("final.csv", index=False)

# Display final merged dataframe
final_df

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status
0,A001,M,Paris,25,John,Alter,2,Project 1,100200.00,Finished
1,A001,M,Paris,25,John,Alter,2,Project 9,2069406.25,Ongoing
2,A001,M,Paris,25,John,Alter,2,Project 11,2000000.00,Failed
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2000000.00,Ongoing
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,680000.00,Failed
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4500000.00,Finished
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,350000.00,Failed
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,300000.00,Finished
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5500000.00,Ongoing
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1000000.00,Ongoing
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3000000.00,Finished
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3025050.00,Finished
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,400000.00,Finished
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,200000.00,Finished

In [19]:
# =========================================================
# TASK 5: Calculate and Add a 5% Bonus for Finished Projects
# =========================================================

In [20]:
# Load final dataframe from previous task
final_df = pd.read_csv("final.csv")

# Create Bonus column
final_df["Bonus"] = 0.0

# Give 5% bonus for finished projects
final_df.loc[
    final_df["Status"] == "Finished",
    "Bonus"
] = final_df["Cost"] * 0.05

# Save updated dataframe
final_df.to_csv("final.csv", index=False)

# Display updated dataframe
final_df

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project 1,100200.00,Finished,5010.0
1,A001,M,Paris,25,John,Alter,2,Project 9,2069406.25,Ongoing,0.0
2,A001,M,Paris,25,John,Alter,2,Project 11,2000000.00,Failed,0.0
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2000000.00,Ongoing,0.0
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,680000.00,Failed,0.0
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4500000.00,Finished,225000.0
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,350000.00,Failed,0.0
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,300000.00,Finished,15000.0
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5500000.00,Ongoing,0.0
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1000000.00,Ongoing,0.0
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3000000.00,Finished,150000.0
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3025050.00,Finished,151252.5
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,400000.00,Finished,20000.0
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,200000.00,Finished,10000.0

In [21]:
# =========================================================
# TASK 6: Demote Employees with Failed Projects and Remove
# Employees with Designation Levels Above 4
# =========================================================

In [22]:
# Load final dataframe from previous task
final_df = pd.read_csv("final.csv")

# Find employees with failed projects
failed_ids = final_df[final_df["Status"] == "Failed"]["ID"]

# Find all rows belonging to failed employees
failed_mask = final_df["ID"].isin(failed_ids)

# Reduce designation level by 1
final_df.loc[failed_mask, "Designation Level"] -= 1

# Keep employees with designation level 4 or below
final_df = final_df[final_df["Designation Level"] <= 4]

# Save updated dataframe
final_df.to_csv("final.csv", index=False)

# Display updated dataframe
final_df

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,1,Project 1,100200.00,Finished,5010.0
1,A001,M,Paris,25,John,Alter,1,Project 9,2069406.25,Ongoing,0.0
2,A001,M,Paris,25,John,Alter,1,Project 11,2000000.00,Failed,0.0
3,A002,F,London,27,Alice,Luxumberg,1,Project 2,2000000.00,Ongoing,0.0
4,A002,F,London,27,Alice,Luxumberg,1,Project 6,680000.00,Failed,0.0
5,A003,M,Berlin,29,Tom,Sabestine,2,Project 3,4500000.00,Finished,225000.0
6,A003,M,Berlin,29,Tom,Sabestine,2,Project 8,350000.00,Failed,0.0
7,A003,M,Berlin,29,Tom,Sabestine,2,Project 10,300000.00,Finished,15000.0
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5500000.00,Ongoing,0.0
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1000000.00,Ongoing,0.0
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3000000.00,Finished,150000.0
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3025050.00,Finished,151252.5
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,400000.00,Finished,20000.0
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,200000.00,Finished,10000.0

In [23]:
# =========================================================
# TASK 7: Add Titles to First Names and Remove the Gender Column
# =========================================================

In [24]:
# Load final dataframe from previous task
final_df = pd.read_csv("final.csv")

# Loop through each row
for index, row in final_df.iterrows():

    gender = row["Gender"]
    first_name = row["First Name"]

    # Add title based on gender
    if gender == "M":
        first_name = "Mr. " + first_name
    else:
        first_name = "Mrs. " + first_name

    # Update first name in dataframe
    final_df.loc[index, "First Name"] = first_name

# Remove Gender column
final_df.drop("Gender", axis=1, inplace=True)

# Save updated dataframe
final_df.to_csv("final.csv", index=False)

# Display result
final_df

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,1,Project 1,100200.00,Finished,5010.0
1,A001,Paris,25,Mr. John,Alter,1,Project 9,2069406.25,Ongoing,0.0
2,A001,Paris,25,Mr. John,Alter,1,Project 11,2000000.00,Failed,0.0
3,A002,London,27,Mrs. Alice,Luxumberg,1,Project 2,2000000.00,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,1,Project 6,680000.00,Failed,0.0
5,A003,Berlin,29,Mr. Tom,Sabestine,2,Project 3,4500000.00,Finished,225000.0
6,A003,Berlin,29,Mr. Tom,Sabestine,2,Project 8,350000.00,Failed,0.0
7,A003,Berlin,29,Mr. Tom,Sabestine,2,Project 10,300000.00,Finished,15000.0
8,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 4,5500000.00,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 12,1000000.00,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 13,3000000.00,Finished,150000.0
11,A005,Madrid,30,Mrs. Amy,Johny,3,Project 5,3025050.00,Finished,151252.5
12,A005,Madrid,30,Mrs. Amy,Johny,3,Project 7,400000.00,Finished,20000.0
13,A005,Madrid,30,Mrs. Amy,Johny,3,Project 14,200000.00,Finished,10000.0

In [25]:
# =========================================================
# TASK 8: Promote Employees Older Than 29 Years Using an IF Condition
# =========================================================

In [26]:
# Load final dataframe from previous task
final_df = pd.read_csv("final.csv")

# Loop through each employee record
for index, row in final_df.iterrows():

    # Get employee age and designation level
    age = row["Age"]
    designation_level = row["Designation Level"]

    # Promote employees older than 29 years
    if age > 29:
        designation_level -= 1

    # Update designation level in dataframe
    final_df.loc[index, "Designation Level"] = designation_level

# Save updated dataframe
final_df.to_csv("final.csv", index=False)

# Display updated dataframe
final_df

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,1,Project 1,100200.00,Finished,5010.0
1,A001,Paris,25,Mr. John,Alter,1,Project 9,2069406.25,Ongoing,0.0
2,A001,Paris,25,Mr. John,Alter,1,Project 11,2000000.00,Failed,0.0
3,A002,London,27,Mrs. Alice,Luxumberg,1,Project 2,2000000.00,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,1,Project 6,680000.00,Failed,0.0
5,A003,Berlin,29,Mr. Tom,Sabestine,2,Project 3,4500000.00,Finished,225000.0
6,A003,Berlin,29,Mr. Tom,Sabestine,2,Project 8,350000.00,Failed,0.0
7,A003,Berlin,29,Mr. Tom,Sabestine,2,Project 10,300000.00,Finished,15000.0
8,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 4,5500000.00,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 12,1000000.00,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 13,3000000.00,Finished,150000.0
11,A005,Madrid,30,Mrs. Amy,Johny,2,Project 5,3025050.00,Finished,151252.5
12,A005,Madrid,30,Mrs. Amy,Johny,2,Project 7,400000.00,Finished,20000.0
13,A005,Madrid,30,Mrs. Amy,Johny,2,Project 14,200000.00,Finished,10000.0

In [27]:
# =========================================================
# TASK 9: Calculate Total Project Cost for Each Employee
# =========================================================

In [28]:
# Load final dataframe
final_df = pd.read_csv("final.csv")

# Create TotalProjCost dataframe
TotalProjCost = final_df.groupby("ID").agg({
    "First Name": "first",
    "Cost": "sum"
})

# Convert ID index into a normal column
TotalProjCost = TotalProjCost.reset_index()

# Rename Cost column to Total Cost
TotalProjCost = TotalProjCost.rename(columns={"Cost": "Total Cost"})

# Save TotalProjCost dataframe
TotalProjCost.to_csv("TotalProjCost.csv", index=False)

# Display result
TotalProjCost

     ID  First Name  Total Cost
0  A001    Mr. John  4169606.25
1  A002  Mrs. Alice  2680000.00
2  A003     Mr. Tom  5150000.00
3  A004   Mrs. Nina  9500000.00
4  A005    Mrs. Amy  3625050.00

In [29]:
# =========================================================
# TASK 10: Display Employee Details Where City Contains 'o'
# =========================================================

In [30]:
# Load final dataframe
final_df = pd.read_csv("final.csv")

# Filter employees whose city contains the letter 'o'
result_df = final_df[final_df["City"].str.contains("o", case=False)]

# Display result
result_df

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
3,A002,London,27,Mrs. Alice,Luxumberg,1,Project 2,2000000.0,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,1,Project 6,680000.0,Failed,0.0
8,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 4,5500000.0,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 12,1000000.0,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 13,3000000.0,Finished,150000.0